from .linxutil.multipurpose_configuration import (
    NODE_CLASS_MAPPINGS as MPC_NODE_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as MPC_NAME_MAP,
)
from .linxutil.auto_color_match import (
    NODE_CLASS_MAPPINGS as ACM_NODE_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as ACM_NAME_MAP,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(MPC_NODE_MAP)
NODE_CLASS_MAPPINGS.update(ACM_NODE_MAP)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(MPC_NAME_MAP)
NODE_DISPLAY_NAME_MAPPINGS.update(ACM_NAME_MAP)
