from .linxutil.multipurpose_configuration import (
    NODE_CLASS_MAPPINGS as MPC_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as MPC_NAME,
)
from .linxutil.auto_color_match import (
    NODE_CLASS_MAPPINGS as ACM_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as ACM_NAME,
)
from .linxutil.remove_extension import (
    NODE_CLASS_MAPPINGS as STRIP_EXT_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as STRIP_EXT_NAME,
)

# NEW
from .linxutil.auto_crop_borders import (
    NODE_CLASS_MAPPINGS as ACB_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as ACB_NAME,
)
from .linxutil.levels_match_node import (
    NODE_CLASS_MAPPINGS as LVM_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as LVM_NAME,
)
from .linxutil.crop_by_margins import (
    NODE_CLASS_MAPPINGS as CBM_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as CBM_NAME,
)
from .linxutil.filename_append_suffix import (
    NODE_CLASS_MAPPINGS as FAS_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as FAS_NAME,
)
from .linxutil.stitch_by_mask_feathered import (
    NODE_CLASS_MAPPINGS as SBM_MAP,
    NODE_DISPLAY_NAME_MAPPINGS as SBM_NAME,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(MPC_MAP)
NODE_CLASS_MAPPINGS.update(ACM_MAP)
NODE_CLASS_MAPPINGS.update(STRIP_EXT_MAP)
NODE_CLASS_MAPPINGS.update(ACB_MAP)
NODE_CLASS_MAPPINGS.update(LVM_MAP)
NODE_CLASS_MAPPINGS.update(CBM_MAP)
NODE_CLASS_MAPPINGS.update(FAS_MAP)
NODE_CLASS_MAPPINGS.update(SBM_MAP)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(MPC_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(ACM_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(STRIP_EXT_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(ACB_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(LVM_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(CBM_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(FAS_NAME)
NODE_DISPLAY_NAME_MAPPINGS.update(SBM_NAME)
