# Expose NODE_CLASS_MAPPINGS (and display names) for ComfyUI loader.
from .linxutil.multipurpose_configuration import (
    NODE_CLASS_MAPPINGS as MPC_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MPC_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(MPC_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(MPC_NODE_DISPLAY_NAME_MAPPINGS)
